### ISSUE TITLE
Rohit - HTML Basics Remake

### ISSUE THREAD

**Issue by aravindvnair99** [aravindvnair99/ACM-Amrita-2019-2020-Assignments#9]
@rohitraju1966 Tag this when sending in your pull request.

**Comment by aravindvnair99** [comment]
@rohitraju1966 Merged #2 but remove the duplicate file.

**Comment by aravindvnair99** [comment]
Fixed in #17 and #2

**Comment by VinayakTekade** [comment]
@rohitraju1966 Fixes Required
- Use HTML5 tags
- Superscript the number in square brackets
- The contents list is wrong
- The books list should have italicised brackets

**Comment by VinayakTekade** [comment]
Assignment 1 completed
